name: Build using .NET Core

on:
  push:
    branches: [ 3.0 ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.201

      - name: Install dependencies
        run: dotnet restore

      - name: Build Discord.Net
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --no-restore --verbosity normal

      - name: Pack Discord.Net
        run: dotnet pack --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: nupkgs
          path: $GITHUB_WORKSPACE/artifacts/pkg/
